env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
reportUnusedDisableDirectives: true
rules:
  '@typescript-eslint/no-non-null-assertion': 'off'
  '@typescript-eslint/ban-types':
    - error
    - types:
        object: false
