plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-atelier-workspace.cjs
    spec: '@yarnpkg/plugin-atelier-workspace'

yarnPath: .yarn/releases/yarn-2.4.0.cjs
