plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-snuggery.cjs
    spec: '@yarnpkg/plugin-snuggery'
  - path: .yarn/plugins/@yarnpkg/plugin-snuggery-workspace.cjs
    spec: '@yarnpkg/plugin-snuggery-workspace'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'

changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

changesetIgnorePatterns:
  - '**/__tests__/**'

npmPublishAccess: public

packageExtensions:
  '@nrwl/devkit@*':
    peerDependencies:
      '@angular-devkit/architect': '*'
      rxjs: '*'
  '@nrwl/jest@*':
    dependencies:
      '@angular-devkit/architect': '>= 0.1100.0 < 0.1200.0'
    peerDependencies:
      jest: '*'

preferDeferredVersions: true

yarnPath: .yarn/releases/yarn-2.4.0.cjs
