on:
  push:
    branches:
      - main
  pull_request:

name: 'CI'
jobs:
  codestyle:
    name: 'Codestyle'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install
        shell: bash
        env:
          YARN_ENABLE_NETWORK: 0
        run: |
          yarn install --immutable --immutable-cache

      - name: 'Check for formatting errors (fix w/ "yarn prettier --write path/to/file")'
        run: |
          yarn prettier --check .
        shell: bash

      - name: 'Check for linting errors (fix w/ "yarn lint -c fix")'
        run: |
          yarn ai lint
        shell: bash

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Build
        shell: bash
        run: |
          yarn ai build

      - uses: actions/upload-artifact@v2
        with:
          name: atelier-build
          path: packages/*/dist/
          if-no-files-found: error

  unit:
    name: 'Unit tests'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'Use Node.js ${{matrix.node}}.x'
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: 'Run tests'
        shell: bash
        run: |
          yarn ai test

  integration:
    name: 'Integration tests on node.js ${{matrix.node}}.x'
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node:
          - 12
          - 14
          - 15

    steps:
      - uses: actions/checkout@v2

      - name: 'Use Node.js ${{matrix.node}}.x'
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}.x

      - uses: actions/download-artifact@v2
        with:
          name: atelier-build
          path: packages/

      - name: 'Run tests'
        shell: bash
        run: |
          yarn ai test integration
